### ISSUE TITLE
final cost and running cost

### ISSUE THREAD

**Issue by egoiss** [MRzNone/ilqr#1]
Hi, thanks for your ilqr Algoritms!!!  I try to understand the code but the "final cost" and "running cost" equation, how you got it?

**Comment by MRzNone** [comment]
This is following this [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6386025).  Final cost refers to the cost you want to minimize in order to get to the goal state. Running cost refers to the cost each step takes (e.g. higher force if worse than lower one in most cases).
